# Generated by Django 5.2.13 on 2026-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='标题')),
                ('artist', models.CharField(blank=True, max_length=120, verbose_name='作者')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('audio_file', models.FileField(blank=True, null=True, upload_to='tracks/audio/', verbose_name='音频文件')),
                ('cover_theme', models.CharField(default='summer', max_length=40, verbose_name='封面主题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('likes', models.PositiveIntegerField(default=0, verbose_name='点赞数')),
                ('plays', models.PositiveIntegerField(default=0, verbose_name='播放数')),
            ],
            options={
                'verbose_name': '音频作品',
                'verbose_name_plural': '音频作品',
                'ordering': ['-created_at'],
            },
        ),
    ]
