# Generated by Django 5.2.13 on 2026-05-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracks', '0002_track_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='duration_ms',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('hidden', 'Hidden'), ('deleted', 'Deleted')], default='published', max_length=20),
        ),
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['status', '-created_at'], name='tracks_trac_status_56f49d_idx'),
        ),
    ]
