# Generated by Django 5.2.13 on 2026-05-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='专辑名')),
                ('creator', models.CharField(blank=True, max_length=120, verbose_name='创建者')),
                ('description', models.TextField(blank=True, verbose_name='简介')),
                ('cover_theme', models.CharField(default='summer', max_length=40, verbose_name='封面主题')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '专辑',
                'verbose_name_plural': '专辑',
                'ordering': ['-created_at'],
            },
        ),
    ]
