# Generated by Django 5.2.13 on 2026-05-07 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='cover_image',
            field=models.FileField(blank=True, null=True, upload_to='albums/covers/', verbose_name='封面图片'),
        ),
    ]
