# Generated by Django 5.2.13 on 2026-05-08 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_album_cover_image'),
        ('tracks', '0003_track_duration_ms_track_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbumTrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(default=0)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_tracks', to='albums.album')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_tracks', to='tracks.track')),
            ],
            options={
                'ordering': ['position', 'added_at'],
            },
        ),
        migrations.AddField(
            model_name='album',
            name='tracks',
            field=models.ManyToManyField(blank=True, related_name='albums', through='albums.AlbumTrack', to='tracks.track'),
        ),
        migrations.AddIndex(
            model_name='albumtrack',
            index=models.Index(fields=['album', 'position'], name='albums_albu_album_i_d429f9_idx'),
        ),
        migrations.AddIndex(
            model_name='albumtrack',
            index=models.Index(fields=['track', 'added_at'], name='albums_albu_track_i_eb8282_idx'),
        ),
        migrations.AddConstraint(
            model_name='albumtrack',
            constraint=models.UniqueConstraint(fields=('album', 'track'), name='unique_album_track'),
        ),
    ]
