# Generated by Django 5.2.13 on 2026-05-08 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0002_track_cover_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('body', models.TextField()),
                ('timestamp_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('published', '已发布'), ('pending', '待审核'), ('hidden', '已隐藏'), ('deleted', '已删除')], default='published', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_question', models.BooleanField(default=False)),
                ('is_creator_reply', models.BooleanField(default=False)),
                ('like_count', models.PositiveIntegerField(default=0)),
                ('reply_count', models.PositiveIntegerField(default=0)),
                ('report_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='comments.trackcomment')),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='tracks.track')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-is_pinned', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackCommentReaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reaction', models.CharField(default='like', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='comments.trackcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='trackcomment',
            index=models.Index(fields=['track', '-is_pinned', '-like_count', '-created_at'], name='comments_tr_track_i_c5db5b_idx'),
        ),
        migrations.AddIndex(
            model_name='trackcomment',
            index=models.Index(fields=['track', 'status', '-created_at'], name='comments_tr_track_i_2e0bae_idx'),
        ),
        migrations.AddIndex(
            model_name='trackcomment',
            index=models.Index(fields=['track', 'is_question', '-created_at'], name='comments_tr_track_i_f51893_idx'),
        ),
        migrations.AddIndex(
            model_name='trackcomment',
            index=models.Index(fields=['parent', 'created_at'], name='comments_tr_parent__3d91bf_idx'),
        ),
        migrations.AddConstraint(
            model_name='trackcommentreaction',
            constraint=models.UniqueConstraint(fields=('comment', 'user', 'reaction'), name='unique_comment_user_reaction'),
        ),
    ]
