# Generated by Django 5.2.13 on 2026-05-08 03:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('tracks', '0003_track_duration_ms_track_status_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trackcomment',
            name='reply_to_user_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddIndex(
            model_name='trackcomment',
            index=models.Index(fields=['track', 'parent', 'status', 'created_at'], name='comments_tr_track_i_5936db_idx'),
        ),
    ]
