# Generated by Django 5.2.13 on 2026-05-08 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tracks', '0002_track_cover_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackLyrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(default='zh-Hans', max_length=20)),
                ('kind', models.CharField(choices=[('original', '原文'), ('translation', '翻译'), ('romanized', '罗马音'), ('word_by_word', '逐词')], default='original', max_length=20)),
                ('source_file', models.FileField(blank=True, null=True, upload_to='tracks/lyrics/')),
                ('raw_text', models.TextField(blank=True)),
                ('parser_version', models.CharField(blank=True, max_length=40)),
                ('is_primary', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lyrics_sets', to='tracks.track')),
            ],
            options={
                'ordering': ['-is_primary', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TrackLyricLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_ms', models.PositiveIntegerField(default=0)),
                ('end_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('translation', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('lyrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='lyrics.tracklyrics')),
            ],
            options={
                'ordering': ['position', 'start_ms'],
            },
        ),
        migrations.AddConstraint(
            model_name='tracklyrics',
            constraint=models.UniqueConstraint(fields=('track', 'language', 'kind'), name='unique_track_lyrics_variant'),
        ),
        migrations.AddIndex(
            model_name='tracklyricline',
            index=models.Index(fields=['lyrics', 'start_ms'], name='lyrics_trac_lyrics__1aff79_idx'),
        ),
        migrations.AddIndex(
            model_name='tracklyricline',
            index=models.Index(fields=['lyrics', 'position'], name='lyrics_trac_lyrics__2f702d_idx'),
        ),
    ]
