# Generated by Django 5.2.13 on 2026-05-08 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lyrics', '0001_initial'),
        ('tracks', '0003_track_duration_ms_track_status_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='tracklyrics',
            index=models.Index(fields=['track', 'is_primary', '-created_at'], name='lyrics_trac_track_i_957b48_idx'),
        ),
    ]
