# Generated by Codex on 2026-05-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lyrics", "0002_tracklyrics_lyrics_trac_track_i_957b48_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="tracklyrics",
            name="status",
            field=models.CharField(
                choices=[
                    ("available", "有歌词"),
                    ("instrumental", "无歌词的纯音乐"),
                    ("pending", "暂无歌词"),
                ],
                default="available",
                max_length=20,
            ),
        ),
    ]
